version: '3'

services:
  app:
    container_name: projeto-plataforma-node
    build:
      context: ./api
      dockerfile: api/Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3000
    ports:
      - 3000:3000
